# Generated by Django 3.2 on 2021-04-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='user',
        ),
        migrations.DeleteModel(
            name='LogUser',
        ),
        migrations.DeleteModel(
            name='LogWithdraw',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Auth',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
